//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PopStudio.MAUI {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_AD {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_AD() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("PopStudio.MAUI.Resource_AD", typeof(Resource_AD).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AD1 {
            get {
                return ResourceManager.GetString("AD1", resourceCulture);
            }
        }
        
        internal static string AD2 {
            get {
                return ResourceManager.GetString("AD2", resourceCulture);
            }
        }
        
        internal static string AD3 {
            get {
                return ResourceManager.GetString("AD3", resourceCulture);
            }
        }
        
        internal static byte[] ImageAD1 {
            get {
                object obj = ResourceManager.GetObject("ImageAD1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ImageAD2 {
            get {
                object obj = ResourceManager.GetObject("ImageAD2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ImageAD3 {
            get {
                object obj = ResourceManager.GetObject("ImageAD3", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
